### ISSUE TITLE
Add Windows support

### ISSUE THREAD

**Issue by gillstrom** [gillstrom/vol#4]

**Comment by kevva** [comment]
http://nircmd.nirsoft.net/setsysvolume.html

**Comment by gillstrom** [comment]
:+1: 

Need a way to get volume level in order to solve #2.

**Comment by gillstrom** [comment]
http://www.nirsoft.net/utils/sound_volume_view.html

**Comment by EladBezalel** [comment]
:+1: any progress guys?

**Comment by gillstrom** [comment]
Setting the volume shouldn't be any problem with [nircmd](https://www.github.com/gillstrom/nircmd), but I can't find a way to get current volume level.

**Comment by EladBezalel** [comment]
Well after i searched a little bit, there is no easy way (cuz windows),
There's a [cmd tool](http://stackoverflow.com/questions/4640106/get-the-current-system-volume-in-windows-7/4640225#4640225) pre-compiled and compiled that may be the best solution

**Comment by kevva** [comment]
Super nice. Thanks.

**Comment by gillstrom** [comment]
Thank you!

**Comment by EladBezalel** [comment]
Great work! thanks!!

**Comment by futurist** [comment]
also include the `volume.exe` source into the lib?
