### ISSUE TITLE
Windows vol cli alias already in use

### ISSUE THREAD

**Issue by EladBezalel** [gillstrom/vol#5]
I installed it globally and apparently there's already 'vol' command.

**Comment by kevva** [comment]
Just symlink it to something else. I don't know if it's worth renaming this because of it.

**Comment by noamokman** [comment]
we can also add a `volume` alias, would you like me to PR?

**Comment by kevva** [comment]
Yeah, sure.

**Comment by EladBezalel** [comment]
Great! Thanks @noamokman @kevva
